{
 "title": "BuildStuff 2019",
 "time": { "from": "2019-11-06T08:40:05.865Z", "to": "2019-11-06T08:47:17.647Z" },
 "panels": [
  {
   "title": "Player 1",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__unixEpochGroupAlias(time,1s),\n  avg(attentionlevel_player1) AS \"attention\",\n  avg(meditation1level_player1) AS \"meditation\",\n  avg(speed_player1) AS \"speed\"\nFROM event\nWHERE\n  $__unixEpochFilter(time)\nGROUP BY 1\nORDER BY $__unixEpochGroup(time,1s)"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 5, "w": 3, "x": 12, "y": 0 }, "content": "<img src=/public/img/bs.gif>" },
  {
   "title": "Current game",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 9, "x": 15, "y": 0 },
   "format": "none",
   "valueName": "max",
   "targets": [
    {
     "rawSql": "select max(race_id) from event;"
    }
   ]
  },
  {
   "title": "Leaderboard",
   "type": "table",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 3 },
   "targets": [
    {
     "rawSql": "select max(users.id) as reg_id, \nrace_id, \napi_pc_id as car_id, \nusername, \nemail,  \nCASE WHEN api_pc_id = 1 THEN (lap1time_player1 + lap2time_player1 + lap3time_player1)/1000 ELSE (lap1time_player2 + lap2time_player2 + lap3time_player2)/1000 END AS best_time,\ndate\nfrom users\nINNER JOIN users_results ON users.api_pc_id = users_results.which_player_caused AND users.game_id = users_results.race_id\nWHERE users_results.event_name = 'raceFinished' \nGROUP BY api_pc_id, race_id\nORDER BY best_time"
    }
   ]
  },
  {
   "title": "Max_speed",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 5 },
   "format": "none",
   "valueName": "max",
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  max_speed_settings_player1\nFROM event\nWHERE\n  $__unixEpochFilter(time)\nORDER BY time"
    }
   ]
  },
  {
   "title": "Average speed",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__unixEpochGroupAlias(time,1s),\n  avg(speed_player1) AS \"attentionlevel_player1\"\nFROM event\nWHERE\n  $__unixEpochFilter(time)\nGROUP BY 1\nORDER BY $__unixEpochGroup(time,1s)"
    }
   ]
  },
  {
   "title": "Player 2",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__unixEpochGroupAlias(time,1s),\n  avg(attentionlevel_player2) AS \"attention\",\n  avg(meditation2level_player2) AS \"meditation\",\n  avg(speed_player2) AS \"speed\"\nFROM event\nWHERE\n  $__unixEpochFilter(time)\nGROUP BY 1\nORDER BY $__unixEpochGroup(time,1s)"
    }
   ]
  },
  {
   "title": "Leaderboard",
   "type": "table",
   "gridPos": { "h": 16, "w": 9, "x": 15, "y": 12 },
   "targets": [
    {
     "rawSql": "SELECT\n  game_id,\n  max(id) as id,\n  username,\n  email,\n  api_pc_id as car_id,\n  date\nFROM users\nWHERE leaderboard <> 'false'\nGROUP BY username, email\n"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 4, "w": 3, "x": 12, "y": 13 }, "content": "<img src=/public/img/bs.gif>" },
  {
   "title": "Max_speed",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 17 },
   "format": "none",
   "valueName": "max",
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  max_speed_settings_player2\nFROM event\nWHERE\n  $__unixEpochFilter(time)\nORDER BY time"
    }
   ]
  },
  {
   "title": "Average speed",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 19 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__unixEpochGroupAlias(time,1s),\n  avg(speed_player2) AS \"attentionlevel_player1\"\nFROM event\nWHERE\n  $__unixEpochFilter(time)\nGROUP BY 1\nORDER BY $__unixEpochGroup(time,1s)"
    }
   ]
  }
 ]
}