{
 "title": "BuildStuff 2019",
 "time": { "from": "2019-11-11T14:09:15.099Z", "to": "2019-11-11T14:09:49.185Z" },
 "panels": [
  {
   "title": "Player 1",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__unixEpochGroupAlias(time,1s),\n  avg(attentionlevel_player1) AS \"attention\",\n  avg(speed_player1) AS \"speed\"\nFROM event\nWHERE\n  $__unixEpochFilter(time)\nGROUP BY 1\nORDER BY $__unixEpochGroup(time,1s)"
    }
   ]
  },
  {
   "title": "G Force meter (m/s^2)",
   "type": "natel-plotly-panel",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__unixEpochGroupAlias(time,1s),\n  avg(gforcex_player1) AS \"gforcex_player1\",\n  avg(gforcey_player1) AS \"gforcey_player1\"\nFROM event\nWHERE\n  $__unixEpochFilter(time)\nGROUP BY 1\nORDER BY $__unixEpochGroup(time,1s)"
    }
   ]
  },
  {
   "title": "Current game",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "max",
   "targets": [
    {
     "rawSql": "select max(race_id) from event;"
    }
   ]
  },
  {
   "title": "Leaderboard",
   "type": "table",
   "gridPos": { "h": 15, "w": 8, "x": 16, "y": 4 },
   "targets": [
    {
     "rawSql": "select \nmax(users.id) as reg_id,\nrace_id, \napi_pc_id as car_id, \nusername, \nwhole_race_time_player2/1000 as total_time,\ndate\nfrom users\nINNER JOIN users_results ON  users.game_id = users_results.race_id AND users.api_pc_id = users_results.which_player_caused\nWHERE users_results.event_name = 'raceFinished' AND api_pc_id = 1\nGROUP BY api_pc_id, race_id\n\nUNION ALL\n\nselect\nmax(users.id) as reg_id,\nrace_id, \napi_pc_id as car_id, \nusername, \nwhole_race_time_player1/1000 as total_time,\ndate\nfrom users\nINNER JOIN users_results ON  users.game_id = users_results.race_id AND users.api_pc_id = users_results.which_player_caused\nWHERE users_results.event_name = 'raceFinished' AND api_pc_id = 0 \nGROUP BY api_pc_id, race_id\nORDER BY total_time"
    }
   ]
  },
  {
   "title": "Speed",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__unixEpochGroupAlias(time,1s),\n  avg(speed_player1) AS \"speed\"\nFROM event\nWHERE\n  $__unixEpochFilter(time)\nGROUP BY 1\nORDER BY $__unixEpochGroup(time,1s)"
    }
   ]
  },
  {
   "title": "Player 2",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__unixEpochGroupAlias(time,1s),\n  avg(attentionlevel_player2) AS \"attention\",\n  avg(speed_player2) AS \"speed\"\nFROM event\nWHERE\n  $__unixEpochFilter(time)\nGROUP BY 1\nORDER BY $__unixEpochGroup(time,1s)"
    }
   ]
  },
  {
   "title": "G Force meter (m/s^2)",
   "type": "natel-plotly-panel",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 13 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__unixEpochGroupAlias(time,1s),\n  avg(gforcex_player2) AS \"gforcex_player1\",\n  avg(gforcey_player2) AS \"gforcey_player1\"\nFROM event\nWHERE\n  $__unixEpochFilter(time)\nGROUP BY 1\nORDER BY $__unixEpochGroup(time,1s)"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 14, "w": 8, "x": 16, "y": 19 }, "content": "<img src=/public/img/bs.gif>" },
  {
   "title": "Speed",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 20 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__unixEpochGroupAlias(time,1s),\n  avg(speed_player2) AS \"speed\"\nFROM event\nWHERE\n  $__unixEpochFilter(time)\nGROUP BY 1\nORDER BY $__unixEpochGroup(time,1s)"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 7, "w": 16, "x": 0, "y": 26 }, "content": "<img src=/public/img/flow.png>" },
  {
   "title": "Leaderboard debug",
   "type": "table",
   "gridPos": { "h": 5, "w": 6, "x": 17, "y": 33 },
   "targets": [
    {
     "rawSql": "SELECT\n  game_id,\n  max(id) as id,\n  username,\n  email,\n  api_pc_id as car_id,\n  date\nFROM users\nWHERE leaderboard <> 'false'\nGROUP BY username, email\n"
    }
   ]
  }
 ]
}